# Generated by Django 4.2.13 on 2026-08-24 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_appointment_reassignment_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('booking_confirmed', 'Booking confirmed'), ('booking_cancelled', 'Booking cancelled'), ('booking_rescheduled', 'Booking rescheduled'), ('doctor_absent', 'Doctor marked absent'), ('reschedule_offer', 'Reschedule offered'), ('running_late', 'Doctor running late'), ('follow_up_available', 'Follow-up available'), ('visit_summary_ready', 'Visit summary ready'), ('medication_reminder', 'Medication reminder')], max_length=30),
        ),
        migrations.CreateModel(
            name='MedicationReminderLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_date', models.DateField(db_index=True)),
                ('time_slot', models.CharField(blank=True, default='morning', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='medication_reminders', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(db_column='prescription_id', on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='clinical.prescription')),
            ],
            options={
                'db_table': 'medication_reminder_logs',
                'indexes': [models.Index(fields=['patient', 'reminder_date'], name='idx_med_remind_patient_date')],
                'unique_together': {('prescription', 'reminder_date', 'time_slot')},
            },
        ),
    ]
