# Generated by Phase 2 — do not edit manually after applying.
from __future__ import annotations

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        # ── DoctorProfile ────────────────────────────────────────────────────
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="doctor_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("specialization", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("google_oauth_connected", models.BooleanField(default=False)),
                ("slot_duration_minutes", models.PositiveSmallIntegerField(default=60)),
                ("slot_capacity", models.PositiveSmallIntegerField(default=5)),
            ],
            options={
                "db_table": "doctor_profiles",
            },
        ),

        # ── ShiftConfig ──────────────────────────────────────────────────────
        migrations.CreateModel(
            name="ShiftConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "doctor",
                    models.OneToOneField(
                        db_column="doctor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_config",
                        to="scheduling.doctorprofile",
                    ),
                ),
                ("shift_1_start", models.TimeField(default="09:00")),
                ("shift_1_end",   models.TimeField(default="13:00")),
                ("shift_2_start", models.TimeField(default="14:00")),
                ("shift_2_end",   models.TimeField(default="17:00")),
                (
                    "working_days",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(),
                        default=list,
                        size=7,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "shift_configs",
            },
        ),

        # ── AppointmentSlot ──────────────────────────────────────────────────
        migrations.CreateModel(
            name="AppointmentSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        db_column="doctor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="scheduling.doctorprofile",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        db_column="hospital_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_slots",
                        to="accounts.hospital",
                    ),
                ),
                ("date",         models.DateField()),
                ("slot_start",   models.TimeField()),
                ("slot_end",     models.TimeField()),
                ("capacity",     models.PositiveSmallIntegerField()),
                ("booked_count", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "appointment_slots",
            },
        ),
        migrations.AddConstraint(
            model_name="appointmentslot",
            constraint=models.UniqueConstraint(
                fields=["doctor", "date", "slot_start"],
                name="uq_slot_doctor_date_start",
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentslot",
            index=models.Index(
                fields=["doctor", "date"], name="idx_slots_doctor_date"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentslot",
            index=models.Index(
                fields=["hospital", "date"], name="idx_slots_hospital_date"
            ),
        ),

        # ── DoctorLeave ──────────────────────────────────────────────────────
        migrations.CreateModel(
            name="DoctorLeave",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        db_column="doctor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_days",
                        to="scheduling.doctorprofile",
                    ),
                ),
                ("date",   models.DateField()),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leave_entries_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "doctor_leave",
            },
        ),
        migrations.AddConstraint(
            model_name="doctorleave",
            constraint=models.UniqueConstraint(
                fields=["doctor", "date"],
                name="uq_leave_doctor_date",
            ),
        ),
        migrations.AddIndex(
            model_name="doctorleave",
            index=models.Index(
                fields=["doctor", "date"], name="idx_leave_doctor_date"
            ),
        ),

        # ── DoctorAttendance ─────────────────────────────────────────────────
        migrations.CreateModel(
            name="DoctorAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        db_column="doctor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="scheduling.doctorprofile",
                    ),
                ),
                ("date",  models.DateField()),
                (
                    "shift",
                    models.CharField(
                        choices=[("morning", "Morning"), ("afternoon", "Afternoon")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("present", "Present"), ("absent", "Absent")],
                        default="absent",
                        max_length=10,
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        db_column="marked_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_marks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("marked_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "doctor_attendance",
            },
        ),
        migrations.AddConstraint(
            model_name="doctorattendance",
            constraint=models.UniqueConstraint(
                fields=["doctor", "date", "shift"],
                name="uq_attendance_doctor_date_shift",
            ),
        ),
        migrations.AddIndex(
            model_name="doctorattendance",
            index=models.Index(
                fields=["doctor", "date"], name="idx_attendance_doctor_date"
            ),
        ),
    ]
