interface Props {
  compact?: boolean
}

export default function AIDisclaimer({ compact = false }: Props) {
  if (compact) {
    return (
      <span className="inline-flex items-center gap-1.5 text-xs text-[#697C70] font-sans">
        <svg width="12" height="12" viewBox="0 0 16 16" fill="none" aria-hidden="true">
          <circle cx="8" cy="8" r="7" stroke="#697C70" strokeWidth="1.5" />
          <path d="M8 5v4M8 11v1" stroke="#697C70" strokeWidth="1.5" strokeLinecap="round" />
        </svg>
        AI-generated for clarity — not medical advice
      </span>
    )
  }

  return (
    <div
      className="flex items-start gap-3 rounded-lg border border-[#B3C9D6] bg-[#EEF4F7] px-4 py-3"
      role="note"
      aria-label="AI-generated content disclaimer"
    >
      <svg
        width="16" height="16" viewBox="0 0 16 16" fill="none"
        aria-hidden="true" className="mt-0.5 shrink-0 text-[#4A7A94]"
      >
        <circle cx="8" cy="8" r="7" stroke="#4A7A94" strokeWidth="1.5" />
        <path d="M8 5v4M8 11v1" stroke="#4A7A94" strokeWidth="1.5" strokeLinecap="round" />
      </svg>
      <p className="text-sm text-[#2A5570] leading-relaxed">
        <strong className="font-medium">AI-assisted summary.</strong>{' '}
        This text was generated by an AI for clarity and reviewed and approved by your doctor.
        It is not medical advice — please follow your doctor's verbal instructions and contact
        the clinic if anything is unclear.
      </p>
    </div>
  )
}
