# Generated by Django 4.2.13 on 2026-08-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_appointment_reassignment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='prescription',
            name='reminder_times',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
